### ISSUE TITLE
[Recife] Macbook Pro Retina 13-inch Early 2015 - Apenas 10 Meses de Uso

### ISSUE THREAD

**Issue by joelcipriano** [frontendbr/compra-e-venda#5]
![macbook-pro-2015-apenas-10-meses-de-uso-D_NQ_NP_977491-MLB29270948384_012019-F](https://user-images.githubusercontent.com/12474297/60288030-b69c2880-98e9-11e9-959a-a9b51fae2d0f.jpg)

### Macbook Pro Retina 13-inch Early 2015

**Apenas 10 meses de uso e ainda com garantia de fábrica**

- Desconfiado com os modelos de 2016, 2017, 2018 e 2019?
- Medo de ter problemas com o teclado novo dos modelos acima?
- Vá de MacBook Pro 2015!
- Excelente máquina com **teclado confiável** e **novo trackpad com Haptic Engine**.

## Características

- Processador: Intel Core i5
- Memória RAM: 8 GB
- Capacidade do SSD: 128 GB
- Resolução da tela: 13,3-inch (2560 x 1600)
- GPU: Intel Iris Graphics 6100 1536 MB
- Tamanho da tela: 13.3 inches
- Memória de vídeo: 1536 MB

## Valor

R$ 5.199,00

## Link para o produto

[Anúncio no Mercado Livre](https://produto.mercadolivre.com.br/MLB-1261732204-macbook-pro-2015-apenas-10-meses-de-uso-_JM?quantity=1&variation=39435351594)
[Review do Jonathan Morrison](https://www.youtube.com/watch?v=cKWAhBDQ2LU)

=================================

## Atenção!

Esse é um espaço apenas para anúncios, toda a negociação é realizada entre o anunciante e o interessado. A Front-End Brasil não se responsabiliza por eventuais desacordos ou demais problemas entre as partes envolvidas.

**Comment by brunocrpontes** [comment]
@joelcipriano você tem algum contato pra eu falar ctg?

**Comment by joelcipriano** [comment]
@joelcipriano, pode ser no joelcipriano@gmail.com?

**Comment by joelcipriano** [comment]
@brunocrpontes, pode ser no joelcipriano@gmail.com?

**Comment by joelcipriano** [comment]
Vendido.
