### ISSUE TITLE
[São Paulo] iMac

### ISSUE THREAD

**Issue by victorcaina** [frontendbr/compra-e-venda#9]
## Características
- Processador: Intel Core i5
- Memória RAM: 4 GB
- Tamanho da tela: 21.5
- GPU: AMD Radeon HD 6750M 512 MB

## Valor
R$ 2.400,00

## Link para o produto

[Anúncio na OLX](https://m.olx.com.br/anuncio?ad_id=633773268)

=================================

## Atenção!

Esse é um espaço apenas para anúncios, toda a negociação é realizada entre o anunciante e o interessado. A Front-End Brasil não se responsabiliza por eventuais desacordos ou demais problemas entre as partes envolvidas.

**Comment by carinebatista** [comment]
Ainda está disponível?
